Write-Host "=== Phase137 Vendor Placeholder Repair ===" -ForegroundColor Cyan

# Ensure directory exists
$dir = "app/vendors/[id]"
if (-not (Test-Path $dir)) {
    Write-Host "[INFO] Creating vendor folder..." -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}

# Path for placeholder file
$path = "app/vendors/[id]/page.tsx"

# Write placeholder file (compatible with PowerShell 5.1)
Write-Host "[INFO] Writing placeholder page.tsx..." -ForegroundColor Yellow

@"
import Link from 'next/link';

export default function VendorPage({ params }) {
  return (
    <div style={{ padding: '40px', fontFamily: 'sans-serif' }}>
      <h1 style={{ fontSize: '32px', marginBottom: '20px' }}>Vendor Placeholder</h1>
      <p>This is a safe placeholder page generated by Phase137.</p>
      <br/>
      <Link href="/vendors">Back to Vendors</Link>
    </div>
  );
}
"@ | Out-File -FilePath $path -Encoding UTF8

Write-Host "[OK] Vendor placeholder file written successfully." -ForegroundColor Green
Write-Host "=== Phase137 Completed ===" -ForegroundColor Green
