<#
.SYNOPSIS
  Phase189 - Project Readiness Snapshot

.DESCRIPTION
  Orchestrates a few key phase scripts (179–182 etc.), records whether they
  ran successfully, and generates a Markdown readiness snapshot under /logs.
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Resolve repo root based on this script location
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot  = Split-Path -Parent $scriptDir
$scriptsDir = Join-Path $repoRoot 'scripts'
$logsDir    = Join-Path $repoRoot 'logs'

if (-not (Test-Path $logsDir)) {
    New-Item -Path $logsDir -ItemType Directory -Force | Out-Null
}

$timestamp   = Get-Date -Format 'yyyy-MM-dd_HH-mm-ss'
$reportFile  = Join-Path $logsDir "Phase189-ProjectReadiness-$timestamp.md"

function Write-PhaseStatus {
    param(
        [string]$Message,
        [string]$Color = 'Cyan'
    )
    Write-Host $Message -ForegroundColor $Color
}

function Append-Report {
    param(
        [string]$Line
    )
    Add-Content -Path $script:reportFile -Value $Line
}

function Run-PhaseScript {
    param(
        [string]$FileName,
        [string]$FriendlyName
    )

    $fullPath = Join-Path $scriptsDir $FileName

    if (-not (Test-Path $fullPath)) {
        Write-PhaseStatus "SKIP: $FriendlyName (missing: $FileName)" 'Yellow'
        return $false
    }

    try {
        Write-PhaseStatus "RUNNING: $FriendlyName via $FileName" 'Cyan'
        & $fullPath
        Write-PhaseStatus "OK: $FriendlyName" 'Green'
        return $true
    }
    catch {
        Write-PhaseStatus "FAILED: $FriendlyName -> $($_.Exception.Message)" 'Red'
        return $false
    }
}

# -----------------------------
# 1) Run key phases (179+)
# -----------------------------
$phaseResults = @()

$phaseResults += [pscustomobject]@{
    Name = 'Phase179 - Env & Project Audit'
    Ran  = (Run-PhaseScript 'Phase179-EnvAndProjectAudit.ps1' 'Phase179 - Env & Project Audit')
}

$phaseResults += [pscustomobject]@{
    Name = 'Phase180 - Vendor Readiness Snapshot'
    Ran  = (Run-PhaseScript 'Phase180-VendorReadinessSnapshot.ps1' 'Phase180 - Vendor Readiness Snapshot')
}

$phaseResults += [pscustomobject]@{
    Name = 'Phase181 - Board Report Snapshot'
    Ran  = (Run-PhaseScript 'Phase181-BoardReportSnapshot.ps1' 'Phase181 - Board Report Snapshot')
}

$phaseResults += [pscustomobject]@{
    Name = 'Phase182 - Evidence Snapshot & Audit'
    Ran  = (Run-PhaseScript 'Phase182-EvidenceAudit.ps1' 'Phase182 - Evidence Snapshot & Audit')
}

$phaseResults += [pscustomobject]@{
    Name = 'Phase183 - API / Route Health Check'
    Ran  = (Run-PhaseScript 'Phase183-APIHealthCheck.ps1' 'Phase183 - API / Route Health Check')
}

# -----------------------------
# 2) Build Markdown report
# -----------------------------

Append-Report "# Truvern Project Readiness Snapshot"
Append-Report ""
Append-Report "> Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Append-Report ""
Append-Report "## Phase execution summary"
Append-Report ""

foreach ($p in $phaseResults) {
    $status = if ($p.Ran) { '✅ Ran' } else { '⚠️ Skipped/Failed' }
    Append-Report "- $($status): **$($p.Name)**"
}

Append-Report ""
Append-Report "## Linked phase summaries (if available)"
Append-Report ""

# Try to harvest any existing summary markdown files from previous phases
# Try to harvest any existing summary markdown files
try {
    $summaryFiles = @(Get-ChildItem -Path $logsDir -Filter 'Phase1*-Summary*.md' -ErrorAction SilentlyContinue)
}
catch {
    $summaryFiles = @()
}

if ($summaryFiles -and $summaryFiles.Count -gt 0) {
    foreach ($s in $summaryFiles) {
        $relPath = [IO.Path]::GetFileName($s.FullName)
        Append-Report "- [$relPath](./$relPath)"
    }
}
else {
    Append-Report "_No existing per-phase summaries were discovered under /logs._"
}

Append-Report ""
Append-Report "## Notes"
Append-Report ""
Append-Report "- This file was generated by **Phase189-ProjectReadiness.ps1**."
Append-Report "- Any phase listed as '⚠️ Skipped/Failed' either did not have a script file present in /scripts or encountered an error during execution."

# -----------------------------
# 3) Final console output
# -----------------------------
Write-PhaseStatus "===== Phase189: Project Readiness Snapshot COMPLETE =====" 'Yellow'
Write-Host "Report written to: $reportFile" -ForegroundColor 'Cyan'
